name: quiz_template
description: 이번 주 주제에 해당하는 퀴즈를 작성해주세요.
title: "[<n>장]: <장 제목>"
labels: ["quiz"]
body:
  - type: markdown
    attributes:
      value: |
        이번 장에 해당하는 퀴즈를 작성해주세요.
  - type: textarea
    id: quiz
    attributes:
      label: 퀴즈
      description: 문제의 질문을 작성해주세요.
      placeholder: 예) 다음 코드에서 타입 체크 결과를 예측해보세요.
    validations:
      required: true
  - type: textarea
    id: answer
    attributes:
      label: 답
      description: |
        (아래 예시를 참고하여 답안을 작성해주세요)
        &lt;details&gt;
        &lt;summary&gt;퀴즈 정답&lt;/summary&gt;
        &lt;div markdown="1"&gt;    
        정답 설명
        &lt;/div&gt;
        &lt;/details&gt;
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        (다음과 같이 답을 작성해 댓글로 달아주세요)
        &lt;details&gt;
        &lt;summary&gt;정답&lt;/summary&gt;
        &lt;div markdown="1"&gt;    
        정답 설명
        &lt;/div&gt;
        &lt;/details&gt;
